# Generated by Django 3.0 on 2019-12-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
